import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
// import ClientSideProviderTest from '@/components/hydration/ClientSideProviderTest'

const inter = Inter({ subsets: ['latin'] })

// for seo we'll need to specify title and description for all the pages
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

//we can also specify a template, here %s will be title from component and later text is appended(| Next App)
export const metadata = {
  title: {default: 'Create Next App',
  template: "%s | Next App"},
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          {/* <ClientSideProviderTest> */}
        <Navbar/>
        {children}
        <Footer/>
        {/* </ClientSideProviderTest> */}
        </div>
        </body>
    </html>
  )
}
